# 1

In [1]:
import numpy as np

with open("input.txt", "r") as f:
    codes = [[int(x) for x in line.strip()] for line in f]

In [2]:
array = np.array(codes)

In [3]:
transpose = array.transpose()
print(transpose)

[[0 0 0 ... 0 0 1]
 [1 1 0 ... 1 1 0]
 [1 1 0 ... 0 0 0]
 ...
 [1 1 1 ... 1 0 1]
 [0 1 0 ... 0 0 0]
 [1 1 1 ... 1 0 0]]


In [4]:
print(array.shape)
threshold = array.shape[0]/2
print(threshold)

(1000, 12)
500.0


In [5]:
sums = [sum(x) for x in transpose]
print(sums)

[492, 511, 507, 521, 488, 502, 510, 528, 512, 509, 492, 488]


In [94]:
gamma_rate = [1 if x>=threshold else 0 for x in sums]
print(gamma_rate)

epsilon_rate = [1 if x<threshold else 0 for x in sums]
print(epsilon_rate)

[0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0]
[1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1]


In [95]:
gamma_rate_int = int(''.join([str(x) for x in gamma_rate]),2)
epsilon_rate_int = int(''.join([str(x) for x in epsilon_rate]),2)

In [96]:
power_consumption = gamma_rate_int*epsilon_rate_int
print(power_consumption)

4174964


# 2

In [202]:
def filter_bit_criteria(candidates:np.array, bit_criterion:str):
    
    assert bit_criterion in ["most", "least"]
    
    array = candidates
    
    # for each bit in the codes
    for bit_index in range(array.shape[1]):
        median = array.shape[0]/2
        # has more ones
        sum_ones = sum(array.transpose()[bit_index])
        #print(median,sum_ones)
        if sum_ones== median:
            criterion = 0 if bit_criterion=="least" else 1
        if sum_ones > median:
            criterion = 0 if bit_criterion=="least" else 1
        if sum_ones < median:
            criterion = 1 if bit_criterion=="least" else 0
         
        
        maybe_excluded = []

        for i, row in enumerate(array):
            if row[bit_index] != criterion:
                maybe_excluded.append(i)
        if len(maybe_excluded) < len(array):
            # Actual substraction of the rows
            array = np.delete(array, maybe_excluded, axis=0)
        else: 
            break
    
    return array[0]

In [203]:
%%time

ogr = filter_bit_criteria(array, "least")
csr = filter_bit_criteria(array, "most")

print(ogr)
print(csr)

[1 1 0 0 1 1 0 0 0 0 0 0]
[0 1 0 1 0 1 0 1 1 0 1 1]
CPU times: user 5.23 ms, sys: 2.21 ms, total: 7.44 ms
Wall time: 11 ms


In [204]:
ogr_int = int(''.join([str(x) for x in ogr]),2)
csr_int = int(''.join([str(x) for x in csr]),2)
print(ogr_int, csr_int)

3264 1371


In [205]:
life_support_rating = ogr_int*csr_int
print(life_support_rating)

4474944
